"""Resolution (pyramid-order) nodes: the 8b DataTree level (issue #15).

Runs against the zagg-written overview fixture (``tests/data/overview_hive``,
generated by ``tools/generate_overview_fixture.py`` — every byte from zagg's
real write path plus its D22 overview sweep, at the zagg sha recorded in
``overview_hive.golden.json``). The goldens pin the expected node roster,
per-order variable sets, per-object ``role``/``zagg_overview`` attrs, and
fold values (count totals, h_min minima), all computed at generation time.

The pins, per the ratified 8b design (concepts page / zagg#201 / spec §4):
manifest-declaration-only node discovery (``pyramid.overview.orders``;
``[]``/absent = today's flat product node, regression-pinned on the
multi-product fixture); ``{product}/{order}`` nodes named by stored cell
order; ``role`` per object, never per node; heterogeneous per-node variable
sets in BOTH directions; helpers over source-order SETS; computed-compose
never a node; zero chunk GETs at open (the counting-store pattern).
"""

import json
import shutil
from pathlib import Path

import numpy as np
import pytest
import xarray as xr

from moczarr import (
    finest_source_at,
    node_objects,
    open_hive,
    open_store,
    overview_orders,
    source_orders,
)
from moczarr.convention import morton_word
from moczarr.pyramid import (
    OBJECTS_ATTR,
    open_overview_order,
    overview_cell_orders,
    overview_declaration,
)

FIXTURE = Path(__file__).parent / "data" / "overview_hive"
GOLDEN = json.loads((Path(__file__).parent / "data" / "overview_hive.golden.json").read_text())
MULTI = Path(__file__).parent / "data" / "multiproduct_hive"


@pytest.fixture()
def root():
    return str(FIXTURE)


@pytest.fixture()
def manifest():
    return json.loads((FIXTURE / "atl06" / "morton_hive.json").read_text())


def _doctored(tmp_path: Path, product: str = "atl06") -> tuple[Path, dict]:
    """A scratch copy of the fixture plus the product's parsed manifest."""
    copy = tmp_path / "overview_hive"
    shutil.copytree(FIXTURE, copy)
    return copy, json.loads((copy / product / "morton_hive.json").read_text())


def _overview_meta(copy: Path, rel: str) -> tuple[Path, dict]:
    path = copy / rel / "zarr.json"
    return path, json.loads(path.read_text())


#: One order-6 overview object of atl06 (an order-4 ancestor node path).
ATL06_OVERVIEW = "atl06/4/3/3/1/2/all.zarr"
#: A SOUTHERN order-4 ancestor node (base cell 5) and one order-6 shard under
#: it — the committed fixture is single-base (``4``), so cross-hemisphere row
#: ordering needs a synthetic graft (:func:`_two_base`).
SOUTH_NODE = "-51111"
SOUTH_SHARD = "-5111111"


def _two_base(tmp_path: Path) -> Path:
    """A fixture copy whose ``atl06`` spans northern AND southern base cells.

    Grafts one southern order-4 ancestor node onto the product: its order-6
    shard joins the root MOC (so the node is a named candidate) and the node
    carries a copy of an existing overview object whose ``morton`` coordinate
    is rewritten to its own 16 order-6 descendants — computed from the digit
    grammar (:func:`rank_tail`), independently of ``moczarr.ranges``, so the
    stored rows are an independent check on the fabricated coordinate.
    """
    import zarr

    from moczarr.convention import rank_tail

    copy, _ = _doctored(tmp_path)
    product = copy / "atl06"
    moc = json.loads((product / "coverage.moc").read_text())
    moc["ranges"].append([SOUTH_SHARD, SOUTH_SHARD])
    (product / "coverage.moc").write_text(json.dumps(moc))
    node = product / "-5" / "1" / "1" / "1" / "1"
    shutil.copytree(product / "4" / "3" / "3" / "1" / "2", node)
    path, meta = _overview_meta(copy, "atl06/-5/1/1/1/1/all.zarr")
    meta["attributes"]["zagg_overview"]["node"] = SOUTH_NODE
    path.write_text(json.dumps(meta))
    words = np.asarray(
        [morton_word(SOUTH_NODE + rank_tail(rank, 2)) for rank in range(16)], dtype=np.uint64
    )
    zarr.open_array(str(node / "all.zarr" / "6" / "morton"), mode="r+")[:] = words
    return copy


class TestDeclarationBinding:
    def test_declared_off_shapes(self):
        # §4.5: branch on pyramid.overview.orders FIRST — absent block,
        # pre-pyramid manifests, the legacy {"orders": []} placeholder, and
        # the canonical declared-off form all mean "no overview family".
        base = {"cell_order": 8, "shard_order": 6}
        for pyramid in (
            None,
            {"orders": [], "aggregation": {}},  # the committed pre-8b fixtures
            {"spec": "zagg-pyramid/1", "overview": {"orders": []}},  # canonical off
        ):
            manifest = dict(base, **({} if pyramid is None else {"pyramid": pyramid}))
            assert overview_declaration(manifest) is None
            assert overview_cell_orders(manifest) == {}

    def test_fixture_declaration_binds(self, manifest):
        decl = overview_declaration(manifest)
        assert decl is not None
        assert decl["orders"] == GOLDEN["products"]["atl06"]["pyramid_orders"]
        # The sweep's materialized actuals are additional keys — tolerated.
        assert "materialized" in decl
        # §4.4 constant depth: k -> c - (s - k), finest first.
        assert overview_cell_orders(manifest) == {4: 6, 2: 4}

    def test_none_class_fields_are_recorded_absence(self, manifest):
        # Option A (the ruled D24 default): a "class": "none" entry carries
        # class ONLY — the zero-open way to know h_mean exists nowhere above
        # native resolution.
        fields = overview_declaration(manifest)["fields"]
        assert fields["h_mean"] == {"class": "none"}
        assert fields["count"]["class"] == "exact"
        assert fields["count"]["method"] == "sum"

    def test_nonempty_orders_require_companions(self, manifest):
        for key in ("spacing", "all_time", "fields"):
            broken = json.loads(json.dumps(manifest))
            del broken["pyramid"]["overview"][key]
            with pytest.raises(ValueError, match=f"MUST all be present.*§4.5|{key}"):
                overview_declaration(broken)

    def test_unknown_pyramid_spec_raises(self, manifest):
        broken = json.loads(json.dumps(manifest))
        broken["pyramid"]["spec"] = "zagg-pyramid/2"
        with pytest.raises(ValueError, match="zagg-pyramid/2"):
            overview_declaration(broken)

    def test_non_ancestor_orders_raise(self, manifest):
        broken = json.loads(json.dumps(manifest))
        broken["pyramid"]["overview"]["orders"] = [6]
        with pytest.raises(ValueError, match="ancestor orders"):
            overview_declaration(broken)


class TestTreeShape:
    def test_order_nodes_under_products(self, root):
        tree = open_store(root, window="2019")
        assert list(tree["atl06"].children) == ["8", "6", "4"]
        assert list(tree["atl06_windows"].children) == ["8", "6"]

    def test_product_node_is_empty_intermediate(self, root, manifest):
        tree = open_store(root, window="2019")
        product = tree["atl06"].to_dataset()
        assert not product.data_vars and not product.coords
        assert product.attrs["semantic_hash"] == manifest["semantic_hash"]
        assert product.attrs["morton_hive"]["cell_order"] == 8

    def test_source_child_is_the_open_hive_dataset(self, root):
        # The source-order child holds exactly the per-product open_hive
        # Dataset, plus the per-object role entries the tree layer surfaces.
        tree = open_store(root, window="2019")
        want = open_hive(root, product="atl06")
        want.attrs[OBJECTS_ATTR] = GOLDEN["products"]["atl06"]["source"]["all"]["objects"]
        xr.testing.assert_identical(tree["atl06"]["8"].to_dataset(), want)

    def test_flat_declaration_regression(self):
        # The multi-product fixture declares no overview family: every
        # product node keeps today's flat form — no order children.
        tree = open_store(str(MULTI), window="2019")
        for name, node in tree.children.items():
            assert not node.children, name
            assert node.ds.sizes["cells"] > 0 or name == "atl06_windows"

    def test_bare_pyramid_store(self, root):
        # A product subtree IS a complete store: opened bare, the degenerate
        # one-child tree grows the same order level under its derived node.
        tree = open_store(f"{root}/atl06")
        assert list(tree.children) == ["atl06"]
        assert list(tree["atl06"].children) == ["8", "6", "4"]
        assert tree.attrs["morton_hive_store"]["bare"] is True

    def test_computed_compose_never_a_node(self, root, manifest):
        # Nodes are exactly the STORED orders the declaration implies —
        # no synthesized composite/order node beyond source + declared.
        tree = open_store(root, window="2019")
        declared = {str(t) for t in overview_cell_orders(manifest).values()}
        assert set(tree["atl06"].children) == declared | {str(manifest["cell_order"])}


class TestRolesAndVariables:
    def test_role_is_per_object(self, root):
        # Every entry carries the object's OWN role attrs — the golden
        # records them from the written bytes, zagg_overview blocks included
        # (the D11 companions: source orders + per-field methods).
        tree = open_store(root, window="2019")
        for order, per_key in GOLDEN["products"]["atl06"]["overviews"].items():
            assert node_objects(tree["atl06"][order]) == per_key["all"]["objects"]

    def test_overview_provenance_carries_d11_companions(self, root):
        tree = open_store(root, window="2019")
        for entry in node_objects(tree["atl06"]["6"]):
            block = entry["zagg_overview"]
            assert block["source_cell_order"] == 8
            assert block["cell_order"] == 6
            assert block["fields"]["count"] == {
                "class": "exact",
                "method": "sum",
                "nan_policy": "skip",
            }

    def test_variable_sets_differ_per_node(self, root):
        # Option A: none-class fields exist ONLY at native resolution;
        # absence at an overview order is an answer, not an error.
        tree = open_store(root, window="2019")
        for order in ("6", "4"):
            got = sorted(tree["atl06"][order].ds.data_vars)
            assert got == GOLDEN["products"]["atl06"]["overviews"][order]["all"]["variables"]
        assert "h_mean" in tree["atl06"]["8"].ds.data_vars
        assert "h_mean" not in tree["atl06"]["6"].ds.data_vars

    def test_option_b_variables_tolerated(self, root, tmp_path):
        # A variable existing at NO source order (a declared derived
        # summary / Phase F field, zagg-side) is the expected case, not
        # corruption: the node's schema comes from its own objects.
        copy, _ = _doctored(tmp_path)
        target = copy / ATL06_OVERVIEW / "6" / "h_extra"
        (target / "c").mkdir(parents=True)
        (target / "zarr.json").write_text(
            json.dumps(
                {
                    "zarr_format": 3,
                    "node_type": "array",
                    "shape": [16],
                    "data_type": "float32",
                    "chunk_grid": {"name": "regular", "configuration": {"chunk_shape": [16]}},
                    "chunk_key_encoding": {"name": "default"},
                    "fill_value": "NaN",
                    "codecs": [{"name": "bytes", "configuration": {"endian": "little"}}],
                    "dimension_names": ["cells"],
                }
            )
        )
        (target / "c" / "0").write_bytes(np.arange(16, dtype="<f4").tobytes())
        tree = open_store(str(copy), window="2019")
        assert "h_extra" in tree["atl06"]["6"].ds.data_vars
        assert "h_extra" not in tree["atl06"]["8"].ds.data_vars

    def test_helpers_range_over_order_sets(self, root):
        tree = open_store(root, window="2019")
        node = tree["atl06"]
        assert source_orders(node) == (8,)
        assert overview_orders(node) == (6, 4)
        assert finest_source_at(node, 8) == 8
        # "At or above order k" is the pyramid sense: <= k numerically.
        with pytest.raises(ValueError, match="no source order"):
            finest_source_at(node, 7)

    def test_helpers_key_on_roles_not_names(self, root, tmp_path):
        # Flip one object's role attrs to source at an overview order: the
        # order joins the source SET while keeping its overview siblings —
        # a mixture node, classified per object.
        copy, _ = _doctored(tmp_path)
        path, meta = _overview_meta(copy, ATL06_OVERVIEW)
        del meta["attributes"]["role"]
        del meta["attributes"]["zagg_overview"]
        path.write_text(json.dumps(meta))
        tree = open_store(str(copy), window="2019")
        node = tree["atl06"]
        assert source_orders(node) == (8, 6)
        assert overview_orders(node) == (6, 4)
        assert finest_source_at(node, 7) == 6
        roles = {entry["node"]: entry["role"] for entry in node_objects(node["6"])}
        assert roles["43312"] == "source" and roles["43314"] == "overview"


class TestFoldParity:
    @pytest.mark.parametrize("order", ["6", "4"])
    def test_atl06_totals_match_golden(self, root, order):
        golden = GOLDEN["products"]["atl06"]["overviews"][order]["all"]
        tree = open_store(root, window="2019")
        ds = tree["atl06"][order].ds
        assert ds.sizes["cells"] == golden["n_cells"]
        assert int(ds["count"].sum()) == golden["count_total"]
        assert float(ds["h_min"].min()) == pytest.approx(golden["h_min_min"])

    @pytest.mark.parametrize("window", ["2019", "2020"])
    def test_windowed_totals_match_golden(self, root, window):
        product = GOLDEN["products"]["atl06_windows"]
        tree = open_store(root, window=window)
        ds = tree["atl06_windows"]["6"].ds
        assert int(ds["count"].sum()) == product["overviews"]["6"][window]["count_total"]
        # Source<->overview parity through the reader, per window.
        assert int(ds["count"].sum()) == int(tree["atl06_windows"]["8"].ds["count"].sum())

    def test_per_window_objects(self, root):
        # Overviews inherit window naming (D23): one call opens the mixed
        # store, the window reaching only the windowed product's orders.
        tree = open_store(root, window="2019")
        assert {e["window"] for e in node_objects(tree["atl06_windows"]["6"])} == {"2019"}
        assert {e["window"] for e in node_objects(tree["atl06"]["6"])} == {None}


class TestScoping:
    def test_aoi_scopes_order_nodes(self, root):
        # One order-4 AOI member: 1 cell at the order-4 node, its 16
        # order-6 descendants at the order-6 node, and the covered source
        # cells below it — the same cover, resolved per node order.
        tree = open_store(root, products=["atl06"], aoi=["43312"])
        assert tree["atl06"]["4"].ds.sizes["cells"] == 1
        assert tree["atl06"]["6"].ds.sizes["cells"] == 16
        source = tree["atl06"]["8"].ds
        assert source.sizes["cells"] > 0
        assert int(source["count"].sum()) == int(tree["atl06"]["6"].ds["count"].sum())

    def test_aoi_empty_keeps_node_schema_correct(self, root):
        # The issue-#4 posture per ORDER node: an AOI outside the product's
        # coverage empties every node (schema intact) instead of changing
        # the tree shape.
        with pytest.warns(UserWarning, match="intersects no coverage"):
            tree = open_store(root, products=["atl06"], aoi=["-5111"])
        assert list(tree["atl06"].children) == ["8", "6", "4"]
        for order in ("8", "6", "4"):
            ds = tree["atl06"][order].ds
            assert ds.sizes["cells"] == 0
            assert "count" in ds.data_vars

    def test_pandas_index_kind_matches_moc(self, root):
        moc = open_store(root, products=["atl06"])
        pandas = open_store(root, products=["atl06"], index_kind="pandas")
        for order in ("8", "6", "4"):
            np.testing.assert_array_equal(
                pandas["atl06"][order].ds["morton"].values,
                moc["atl06"][order].ds["morton"].values,
            )
        assert "morton" not in pandas["atl06"]["6"].ds.xindexes

    def test_cell_ids_fabricated_at_node_order(self, root):
        from moczarr import fabricate_cell_ids

        tree = open_store(root, products=["atl06"])
        for order in ("6", "4"):
            ds = tree["atl06"][order].ds
            words = np.asarray(ds["morton"].values, dtype=np.uint64)
            np.testing.assert_array_equal(
                np.asarray(ds["cell_ids"].values),
                fabricate_cell_ids(words, level=int(order)),
            )


class TestMultiBaseOrdering:
    """Cross-hemisphere row order: candidates ride PACKED WORDS, not decimals."""

    def test_objects_follow_packed_word_order(self, tmp_path):
        # A decimal-string sort would put the southern node FIRST (a leading
        # "-" sorts before every digit); the packed-word order puts it last.
        tree = open_store(str(_two_base(tmp_path)), products=["atl06"])
        nodes = [entry["node"] for entry in node_objects(tree["atl06"]["6"])]
        assert nodes == ["43312", "43314", "43321", "43323", SOUTH_NODE]
        words = [morton_word(node) for node in nodes]
        assert words == sorted(words)

    def test_moc_coordinate_labels_the_right_rows(self, tmp_path):
        # §4.4: the coordinate is row identity. The moc index fabricates it
        # from the accumulated (word-ascending) domain while the pandas path
        # reads the stored arrays in candidate order — they agree only if the
        # candidate order IS word order, so this catches the mislabeling that
        # a single-base fixture cannot see.
        copy = str(_two_base(tmp_path))
        moc = open_store(copy, products=["atl06"])
        pandas = open_store(copy, products=["atl06"], index_kind="pandas")
        stored = np.asarray(pandas["atl06"]["6"].ds["morton"].values, dtype=np.uint64)
        fabricated = np.asarray(moc["atl06"]["6"].ds["morton"].values, dtype=np.uint64)
        np.testing.assert_array_equal(stored, fabricated)
        # The southern node's own 16 descendants are the LAST rows, and the
        # data rides with them (its counts are the grafted object's).
        from moczarr.convention import rank_tail

        assert list(fabricated[-16:]) == [
            morton_word(SOUTH_NODE + rank_tail(rank, 2)) for rank in range(16)
        ]
        north = moc["atl06"]["6"].ds["count"].values[:16]
        np.testing.assert_array_equal(moc["atl06"]["6"].ds["count"].values[-16:], north)


class TestDegradation:
    def test_unstamped_overview_is_debris(self, root, tmp_path):
        copy, _ = _doctored(tmp_path)
        path, meta = _overview_meta(copy, ATL06_OVERVIEW)
        del meta["attributes"]["morton_hive_commit"]
        path.write_text(json.dumps(meta))
        tree = open_store(str(copy), window="2019")
        entries = node_objects(tree["atl06"]["6"])
        assert [e["node"] for e in entries] == ["43314", "43321", "43323"]
        assert tree["atl06"]["6"].ds.sizes["cells"] == 48

    def test_declared_but_unswept_order_omitted_with_warning(self, root, tmp_path):
        copy, manifest = _doctored(tmp_path)
        manifest["pyramid"]["overview"]["orders"] = [5, 4, 2]  # 5 never swept
        (copy / "atl06" / "morton_hive.json").write_text(json.dumps(manifest))
        with pytest.warns(UserWarning, match="order 5.*no.*stamped overview"):
            tree = open_store(str(copy), products=["atl06"])
        assert list(tree["atl06"].children) == ["8", "6", "4"]

    def test_no_root_moc_omits_overview_nodes(self, root, tmp_path):
        # Overviews are never load-bearing: without the source MOC the
        # ancestor nodes cannot be named, so the order nodes are omitted
        # (loudly) while the source child still opens via the walk — which
        # must skip the overview objects it now encounters (their stems are
        # not morton decimals).
        copy, _ = _doctored(tmp_path)
        (copy / "atl06" / "coverage.moc").unlink()
        with pytest.warns(UserWarning, match="no usable root coverage.moc"):
            tree = open_store(str(copy), products=["atl06"])
        assert list(tree["atl06"].children) == ["8"]
        golden = GOLDEN["products"]["atl06"]["source"]["all"]
        assert int(tree["atl06"]["8"].ds["count"].sum()) == golden["count_total"]

    def test_walk_open_hive_skips_overview_objects(self, root, tmp_path):
        # The same hardening for a direct open_hive on a MOC-less pyramid
        # store: the discovery walk yields all.zarr overview objects, and
        # the reader must not try to parse their stems as shard decimals.
        copy, _ = _doctored(tmp_path)
        (copy / "atl06" / "coverage.moc").unlink()
        ds = open_hive(f"{copy}/atl06")
        want = open_hive(str(FIXTURE), product="atl06")
        assert int(ds["count"].sum()) == int(want["count"].sum())
        assert ds.sizes["cells"] == want.sizes["cells"]

    def test_third_role_value_raises(self, root, tmp_path):
        copy, _ = _doctored(tmp_path)
        path, meta = _overview_meta(copy, ATL06_OVERVIEW)
        meta["attributes"]["role"] = "composite"
        path.write_text(json.dumps(meta))
        with pytest.raises(ValueError, match="closed two-value"):
            open_store(str(copy), products=["atl06"])

    def test_unknown_overview_spec_raises(self, root, tmp_path):
        copy, _ = _doctored(tmp_path)
        path, meta = _overview_meta(copy, ATL06_OVERVIEW)
        meta["attributes"]["zagg_overview"]["spec"] = "zagg-overview/2"
        path.write_text(json.dumps(meta))
        with pytest.raises(ValueError, match="zagg-overview/2"):
            open_store(str(copy), products=["atl06"])

    def test_missing_provenance_block_raises(self, root, tmp_path):
        copy, _ = _doctored(tmp_path)
        path, meta = _overview_meta(copy, ATL06_OVERVIEW)
        del meta["attributes"]["zagg_overview"]
        path.write_text(json.dumps(meta))
        with pytest.raises(ValueError, match="zagg_overview"):
            open_store(str(copy), products=["atl06"])

    def test_off_order_overview_raises(self, root, tmp_path):
        copy, _ = _doctored(tmp_path)
        path, meta = _overview_meta(copy, ATL06_OVERVIEW)
        meta["attributes"]["zagg_overview"]["cell_order"] = 7
        path.write_text(json.dumps(meta))
        with pytest.raises(ValueError, match="order 7"):
            open_store(str(copy), products=["atl06"])

    def test_windowed_overview_requires_window(self, root, manifest):
        windows_manifest = json.loads((FIXTURE / "atl06_windows" / "morton_hive.json").read_text())
        with pytest.raises(ValueError, match="pass window="):
            open_overview_order(f"{root}/atl06_windows", windows_manifest, 4)


class TestLaziness:
    @pytest.fixture()
    def recorded(self, monkeypatch):
        """The counting-store pattern (test_open_store.py style)."""
        import obstore

        keys: list[str] = []
        real_get, real_get_async = obstore.get, obstore.get_async

        def record(store_, key, *args, **kwargs):
            keys.append(key)
            return real_get(store_, key, *args, **kwargs)

        def record_async(store_, key, *args, **kwargs):
            keys.append(key)
            return real_get_async(store_, key, *args, **kwargs)

        monkeypatch.setattr(obstore, "get", record)
        monkeypatch.setattr(obstore, "get_async", record_async)
        return keys

    def test_tree_layer_adds_zero_chunk_gets(self, root, recorded, manifest):
        # Laziness is exactly the wrapped opens', per node (the 8a pin,
        # extended to the order level): open_store fetches no COORDINATE
        # chunks on the moc default, and its chunk GETs equal those of the
        # per-node opens it wraps — the order-node layer itself adds only
        # metadata (zarr.json / coverage.moc) requests. (A node spanning
        # several objects still concatenates its data variables at open —
        # open_hive's documented behavior, unchanged here.)
        def chunk_reads():
            return sorted(k for k in recorded if "/c/" in k)

        open_store(root, window="2019")
        via_store = chunk_reads()
        assert [k for k in via_store if "/morton/c" in k or "/cell_ids/c" in k] == []
        recorded.clear()
        windows_manifest = json.loads((FIXTURE / "atl06_windows" / "morton_hive.json").read_text())
        open_hive(root, product="atl06")
        open_hive(root, product="atl06_windows", window="2019")
        for order in overview_cell_orders(manifest):
            open_overview_order(f"{root}/atl06", manifest, order)
        for order in overview_cell_orders(windows_manifest):
            open_overview_order(f"{root}/atl06_windows", windows_manifest, order, window="2019")
        assert via_store == chunk_reads()

    def test_single_object_order_node_stays_fully_lazy(self, root, recorded, manifest):
        # The order-2 declared overview folds to ONE object ("433"), so
        # nothing is concatenated: zero chunk objects at open, and the data
        # read flows on demand.
        ds = open_overview_order(f"{root}/atl06", manifest, 2)
        assert [k for k in recorded if "/c/" in k] == []
        assert (
            int(ds["count"].sum())
            == GOLDEN["products"]["atl06"]["overviews"]["4"]["all"]["count_total"]
        )
        assert [k for k in recorded if "/c/" in k] != []
