"""Spec-conformance decode of the committed zagg-written fixtures (issue #19).

Three fixtures, all produced by zagg's PRODUCTION write path and pinned by
committed expected values computed from the generator's *inputs* (never read
back through a zagg reader), so the reader is pinned, not self-certified:

- ``tests/data/spec/minimal`` and ``tests/data/spec/kitchen_sink`` — the
  spec §7 conformance vectors, vendored **byte-identical** (store bytes and
  ``*.expected.json``, re-verified ``diff -r`` at the merge) from
  englacial/zagg ``main`` at ``9e11e65``. The vectors landed on ``main`` with
  the englacial/zagg#346 rebase merge (``c0493ba``) and are unchanged since;
  the pin tracks current ``main`` so the re-check is a ``diff -r`` against a
  live ref. The branch-era shas ``166e908`` and ``555874b`` are historical.
- ``tests/data/strata_hive`` — the SERC-area strata fixture generated by
  ``tools/generate_strata_fixture.py`` from that same ``166e908`` checkout
  (recorded in ``strata_hive.expected.json`` as ``zagg_version:
  0.39.1.dev44+g166e908e4``), where ``src/zagg`` was byte-identical to
  ``origin/main``. One fixture serving issues #19/#20/#21; its tensor-level
  goldens live in ``tests/data/strata_goldens`` (consumed by
  ``test_hhdc.py``).

Everything here runs **without zagg installed**: decoding is
:mod:`moczarr.ragged` only, and the O11 cross-check is moczarr's own
:func:`moczarr.stats.hash_arrays`. Conformance is byte-exact float32/uint64
— no tolerance (spec §7).
"""

import json
from pathlib import Path

import numpy as np
import pytest
from zarr.storage import LocalStore

from moczarr.ragged import open_ragged, read_cell, read_ragged
from moczarr.stats import combined_hash, hash_arrays

DATA = Path(__file__).parent / "data"
#: fixture name -> (store root, expected.json path).
FIXTURES = {
    "minimal": (DATA / "spec" / "minimal", DATA / "spec" / "minimal.expected.json"),
    "kitchen_sink": (
        DATA / "spec" / "kitchen_sink",
        DATA / "spec" / "kitchen_sink.expected.json",
    ),
    "strata_hive": (DATA / "strata_hive", DATA / "strata_hive.expected.json"),
}
STRATA_FIXTURES = ["kitchen_sink", "strata_hive"]


def _load(name):
    root, expected_path = FIXTURES[name]
    expected = json.loads(expected_path.read_text())
    store = LocalStore(root / expected["leaf"])
    return store, expected


def _digest_field(name):
    return "h_tdigest" if name == "minimal" else "h_tdigest_signal"


def _expected_cells(expected, field):
    """``{morton_word: record}`` for cells whose ``field`` payload is nonempty."""
    return {
        int(cell["morton"]): cell
        for cell in expected["cells"]
        if cell.get(field)  # empty list = empty (0, 2) stratum payload
    }


@pytest.mark.parametrize("name", list(FIXTURES))
class TestDecodedValues:
    def test_digest_cells_match_expected_exactly(self, name):
        store, expected = _load(name)
        field = f"{expected['group']}/{_digest_field(name)}"
        cells = _expected_cells(expected, _digest_field(name))
        out = dict(read_ragged(store, field))
        assert set(out) == set(cells)
        for word, values in out.items():
            golden = np.array(cells[word][_digest_field(name)], dtype=np.float32)
            assert values.dtype == np.float32
            np.testing.assert_array_equal(values, golden)  # byte-exact, no tolerance

    def test_digest_payload_invariants(self, name):
        """Spec §2.1: means ascending, total weight = the exact obs count."""
        store, expected = _load(name)
        field = _digest_field(name)
        cells = _expected_cells(expected, field)
        merged_seen = False
        for word, values in read_ragged(store, f"{expected['group']}/{field}"):
            assert np.all(np.diff(values[:, 0]) >= 0)
            record = cells[word]
            exact = record["n_signal"] if field == "h_tdigest_signal" else record["count"]
            assert float(values[:, 1].sum()) == float(exact)
            merged_seen = merged_seen or bool(np.any(values[:, 1] > 1))
        assert merged_seen  # the 300-obs cell merges centroids (weight > 1)

    def test_empty_chunk_and_fill_cells_decode_empty(self, name):
        """The §1.5 absence sentinel and the §1.1 ``b""`` fill."""
        store, expected = _load(name)
        field = f"{expected['group']}/{_digest_field(name)}"
        per_chunk = expected["cells_per_chunk"]
        empty = expected["empty_chunk"]
        populated = {c["index"] for c in expected["cells"]}
        for cell in range(empty * per_chunk, (empty + 1) * per_chunk):
            assert read_cell(store, field, cell).shape == (0, 2)
        fill = next(i for i in range(per_chunk) if i not in populated)
        assert read_cell(store, field, fill).shape == (0, 2)

    def test_o11_content_hashes_match(self, name):
        """moczarr's own §5 O11 recipe reproduces the recorded hashes."""
        root, _ = FIXTURES[name]
        _store, expected = _load(name)
        hashes = hash_arrays(str(root), expected["leaf"])
        assert hashes == expected["content_hashes"]["arrays"]
        assert combined_hash(hashes) == expected["content_hashes"]["combined"]


@pytest.mark.parametrize("name", STRATA_FIXTURES)
class TestStrataFields:
    def test_located_strata_match_expected(self, name):
        """Payload + row-aligned location words, both strata, byte-exact —
        including the merged-centroid common-ancestor words (§2.2)."""
        store, expected = _load(name)
        for stratum in ("signal", "noise"):
            field = f"h_tdigest_{stratum}"
            cells = _expected_cells(expected, field)
            out = list(read_ragged(store, f"{expected['group']}/{field}", locations=True))
            assert {word for word, _v, _l in out} == set(cells)
            for word, values, locations in out:
                record = cells[word]
                np.testing.assert_array_equal(values, np.array(record[field], dtype=np.float32))
                golden_words = np.array(
                    [int(w) for w in record[f"{field}_locations"]], dtype=np.uint64
                )
                assert locations.dtype == np.uint64
                np.testing.assert_array_equal(locations, golden_words)

    def test_noise_only_cell_has_empty_signal_payload(self, name):
        """The empty ``(0, 2)`` stratum payload: observed cells whose signal
        stratum is empty store ``b""`` — decoded empty, never yielded."""
        store, expected = _load(name)
        noise_only = [c for c in expected["cells"] if c["count"] > 0 and not c["h_tdigest_signal"]]
        assert noise_only  # the fixture pins at least one such cell
        for cell in noise_only:
            values = read_cell(store, f"{expected['group']}/h_tdigest_signal", cell["index"])
            assert values.shape == (0, 2)

    def test_provenance_attrs_on_payload_only(self, name):
        """``stratum``/``signal_threshold`` land on the payload array; the
        locations sibling carries no user attrs (spec §1.2)."""
        store, expected = _load(name)
        group = expected["group"]
        arr, element = open_ragged(store, f"{group}/h_tdigest_signal")
        assert arr.attrs["stratum"] == "signal"
        assert int(arr.attrs["signal_threshold"]) == expected.get("signal_threshold", 2)
        assert element.locations == "h_tdigest_signal_locations"
        sibling, _ = open_ragged(store, f"{group}/{element.locations}")
        assert set(dict(sibling.attrs)) == {"ragged"}
