"""``open_hive`` against the committed SERC fixture (zagg-written bytes).

``tests/data/serc_hive`` is generated by ``tools/generate_serc_fixture.py``
run under a zagg environment — every object in it came from zagg's real
write path, so these are writer↔reader integration tests, not unit tests
against our own fixtures. Regenerate only when the spec moves (and then the
goldens in the other test modules must move with it).
"""

import json
import shutil
from pathlib import Path

import numpy as np
import pytest
import xarray as xr

from moczarr import convention, coverage, open_hive, store

FIXTURE = Path(__file__).parent / "data" / "serc_hive"
#: SERC-area order-6 shard containing the site itself (see the generator).
SERC_SHARD = "4331422"


@pytest.fixture()
def serc():
    return str(FIXTURE)


def _stamped_shards(root):
    envelope = store.load_root_coverage(root)
    return [convention.morton_decimal(int(w)) for w in coverage.ranges_words(envelope)]


class TestFixtureShape:
    def test_store_is_hive(self, serc):
        manifest = store.read_manifest(serc)
        assert manifest["spec"] == convention.HIVE_SPEC
        assert (manifest["cell_order"], manifest["shard_order"]) == (8, 6)
        assert manifest["dataset"] == {"short_name": "ATL06", "version": "007"}

    def test_debris_present(self, serc):
        # The generator writes one templated-but-unstamped leaf; the walk sees
        # it, the root MOC does not list it.
        leaves = list(store.walk_leaves(serc))
        stamped = [rel for rel in leaves if store.read_commit(serc, rel) is not None]
        assert len(leaves) == len(stamped) + 1
        listed = set(_stamped_shards(serc))
        walked = {convention.split_leaf_name(rel.rsplit("/", 1)[-1])[0] for rel in stamped}
        assert walked == listed


class TestOpenHive:
    def test_opens_whole_store(self, serc):
        ds = open_hive(serc)
        manifest = store.read_manifest(serc)
        n_shards = len(_stamped_shards(serc))
        assert ds.sizes["cells"] == n_shards * 16  # 4^(8-6) cells per shard
        # morton/cell_ids are coordinates, ascending in packed-word order.
        assert "morton" in ds.coords and "cell_ids" in ds.coords
        morton = np.asarray(ds["morton"].values, dtype=np.uint64)
        assert (np.diff(morton.astype(np.uint64)) > 0).all()
        # The manifest summary rides the result.
        assert ds.attrs["morton_hive"]["cell_order"] == manifest["cell_order"]
        # The leaf's dggs zarr-convention attrs survive (phase-4 seam).
        assert "dggs" in ds.attrs or "zarr_conventions" in ds.attrs

    def test_data_var_order_is_deterministic(self, serc):
        # zarr-python lists group members in async completion order, so a
        # naive open reshuffles ds.data_vars run to run — non-reproducible
        # reprs and notebook diffs. open_hive sorts them lexically; two
        # consecutive opens must agree (and match sorted order).
        first = list(open_hive(serc).data_vars)
        second = list(open_hive(serc).data_vars)
        assert first == second == sorted(first)

    def test_matches_manual_leaf_open(self, serc):
        # Drop-in claim: one leaf opened by plain xr.open_zarr equals the
        # corresponding slice of open_hive's result.
        rel = convention.leaf_path(SERC_SHARD)
        manual = xr.open_zarr(
            f"{serc}/{rel}", group="8", consolidated=False, zarr_format=3
        ).set_coords(["morton", "cell_ids"])
        ds = open_hive(serc)
        word = convention.morton_word(SERC_SHARD)
        sel = ds.where(
            (ds["morton"] >= np.uint64(word))
            & (ds["morton"] < np.uint64(convention.morton_word(SERC_SHARD + "44") + 1)),
            drop=True,
        )
        assert sel.sizes["cells"] == 16
        np.testing.assert_array_equal(sel["cell_ids"].values, manual["cell_ids"].values)
        np.testing.assert_array_equal(sel["count"].values, manual["count"].values)

    def test_debris_skipped(self, serc):
        # The debris shard's cells never appear in the result.
        leaves = list(store.walk_leaves(serc))
        debris = [rel for rel in leaves if store.read_commit(serc, rel) is None]
        assert len(debris) == 1
        shard, _win = convention.split_leaf_name(debris[0].rsplit("/", 1)[-1])
        ds = open_hive(serc)
        prefixes = {convention.morton_decimal(int(w))[:7] for w in ds["morton"].values}
        assert shard not in prefixes

    def test_aoi_shard_subset(self, serc):
        # AOI = one covered shard: only its 16 cells come back.
        ds = open_hive(serc, aoi=[SERC_SHARD])
        assert ds.sizes["cells"] == 16
        decs = [convention.morton_decimal(int(w)) for w in ds["morton"].values]
        assert all(d.startswith(SERC_SHARD) for d in decs)

    def test_aoi_cell_exact_subset(self, serc):
        # AOI at CELL order: rows are subset exactly (tier 2 truth), not just
        # shard-rejected. Query the shard's one OCCUPIED cell (from the
        # bitmap sidecar — the fixture gives this shard a single data cell).
        rel = convention.leaf_path(SERC_SHARD)
        occupied = store.read_coverage_bitmap(serc, rel)
        assert occupied.size == 1
        cell = convention.morton_decimal(int(occupied[0]))
        ds = open_hive(serc, aoi=[cell])
        assert ds.sizes["cells"] == 1
        assert convention.morton_decimal(int(ds["morton"].values[0])) == cell

    def test_aoi_on_unoccupied_cell_is_no_data(self, serc):
        # MOC-domain semantics: an AOI over a cell the coverage tiers say is
        # empty returns nothing (the tier-0 box rejects the leaf) — fill rows
        # are not data. The box being conservative means SOME fill rows can
        # still come back on box false-positives; none-at-all is the empty
        # case: a schema-correct 0-row dataset plus a UserWarning, never fill
        # rows (issue #4).
        occupied = store.read_coverage_bitmap(serc, convention.leaf_path(SERC_SHARD))
        empty = next(
            SERC_SHARD + a + b
            for a in "1234"
            for b in "1234"
            if convention.morton_word(SERC_SHARD + a + b) not in set(int(w) for w in occupied)
        )
        with pytest.warns(UserWarning, match="intersects no coverage"):
            ds = open_hive(serc, aoi=[empty])
        assert ds.sizes["cells"] == 0

    def test_unknown_leaf_coverage_spec_degrades_to_open(self, serc, tmp_path):
        # D9: an unknown leaf-coverage spec must NOT be half-parsed. The box
        # reject routes through parse_leaf_coverage's strict spec gate, so a
        # future/unknown envelope degrades to "open the leaf" and the tier-2
        # aoi_mask still subsets exactly — never a silent false leaf reject.
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        rel = convention.leaf_path(SERC_SHARD)
        occupied = store.read_coverage_bitmap(str(copy), rel)
        cell = convention.morton_decimal(int(occupied[0]))  # "433142224"
        meta_path = copy / rel / "zarr.json"
        meta = json.loads(meta_path.read_text())
        meta["attributes"][convention.COMMIT_ATTR]["coverage"]["spec"] = "morton-moc/9"
        meta_path.write_text(json.dumps(meta))
        # Sanity: the spec gate now reads this leaf's coverage as absent.
        assert store.read_leaf_coverage(str(copy), rel) is None
        ds = open_hive(str(copy), aoi=[cell])
        assert ds.sizes["cells"] == 1
        assert convention.morton_decimal(int(ds["morton"].values[0])) == cell

    def test_aoi_strings_and_words_agree(self, serc):
        by_str = open_hive(serc, aoi=[SERC_SHARD])
        by_word = open_hive(serc, aoi=np.asarray([convention.morton_word(SERC_SHARD)]))
        np.testing.assert_array_equal(by_str["morton"].values, by_word["morton"].values)

    def test_aoi_outside_coverage_is_empty(self, serc):
        # Issue #4: a miss against a covered store is a data answer — empty
        # dataset plus warning, not a raise (see TestEmptyAoi for the schema).
        with pytest.warns(UserWarning, match="intersects no coverage"):
            ds = open_hive(serc, aoi=["-5112333"])  # southern ocean, not SERC
        assert ds.sizes["cells"] == 0

    def test_not_a_hive_store_raises(self, tmp_path):
        (tmp_path / "empty").mkdir()
        with pytest.raises(ValueError, match="not a hive store root"):
            open_hive(str(tmp_path / "empty"))

    def test_window_on_unwindowed_store_raises(self, serc):
        with pytest.raises(ValueError, match="unwindowed"):
            open_hive(serc, window="2019")


#: An AOI intersecting none of the SERC fixture's coverage (southern ocean).
OUTSIDE = "-5112333"


class TestEmptyAoi:
    """Issue #4: an AOI (or window) over no coverage returns a schema-correct
    empty Dataset plus a ``UserWarning`` — raising is reserved for a store
    with no stamped coverage anywhere (``NoCoverageError``)."""

    def _empty(self, root, **kwargs):
        with pytest.warns(UserWarning, match="intersects no coverage") as record:
            ds = open_hive(root, aoi=[OUTSIDE], **kwargs)
        return ds, record

    def test_schema_matches_nonempty_open(self, serc):
        full = open_hive(serc)
        empty, record = self._empty(serc)
        assert empty.sizes["cells"] == 0
        assert set(empty.data_vars) == set(full.data_vars)
        for name in full.data_vars:
            assert empty[name].dtype == full[name].dtype
            assert empty[name].attrs == full[name].attrs
        assert set(empty.coords) == set(full.coords)
        for name in full.coords:
            assert empty[name].dtype == full[name].dtype
        assert empty.attrs["morton_hive"] == full.attrs["morton_hive"]
        # The warning names the store and lands on user code (stacklevel).
        ours = [w for w in record if "intersects no coverage" in str(w.message)]
        assert serc in str(ours[0].message)
        assert ours[0].filename == __file__

    def test_concat_roundtrips(self, serc):
        # The composability the issue asks for: concat with the empty result
        # is the identity — values equal and, because both sides carry every
        # variable (nothing to fill), dtypes are preserved: no int→float NaN
        # promotion (pinned here, documented in open_hive's docstring).
        # Concat across opens needs index_kind="pandas": the moc default's
        # interval index has no concat (pinned below).
        full = open_hive(serc, index_kind="pandas")
        empty, _ = self._empty(serc, index_kind="pandas")
        cat = xr.concat([empty, full], dim="cells")
        assert cat.sizes["cells"] == full.sizes["cells"]
        for name in full.variables:
            np.testing.assert_array_equal(cat[name].values, full[name].values)
            assert cat[name].dtype == full[name].dtype

    def test_concat_of_moc_indexed_raises(self, serc):
        # The known limitation of the index_kind="moc" default (issue #1
        # phase 7d flip): the interval index has no concat currency, so
        # concatenating two default-opened datasets raises — reopen with
        # index_kind="pandas" for concat workflows (documented in the
        # quickstart/concepts pages and the CHANGELOG).
        full = open_hive(serc)
        empty, _ = self._empty(serc)
        with pytest.raises(NotImplementedError):
            xr.concat([empty, full], dim="cells")

    def test_moc_index_empty(self, serc):
        from moczarr.moc_index import MortonMocIndex

        empty, _ = self._empty(serc, index_kind="moc")
        index = empty.xindexes["morton"]
        assert isinstance(index, MortonMocIndex)
        assert index.size == 0
        assert empty.sizes["cells"] == 0
        assert empty["morton"].dtype == np.uint64
        assert empty["cell_ids"].dtype == np.uint64  # "auto" fabricates empty

    def test_decode_empty(self, serc):
        dggs = pytest.importorskip("moczarr.dggs")
        for kind in ("pandas", "moc"):
            empty, _ = self._empty(serc, decode=True, index_kind=kind)
            assert isinstance(empty.xindexes["morton"], dggs.MortonIndex)
            assert empty.sizes["cells"] == 0

    def test_fabricate_toggles_on_empty(self, serc):
        off, _ = self._empty(serc, index_kind="moc", fabricate_cell_ids=False)
        assert "cell_ids" not in off.variables
        on, _ = self._empty(serc, fabricate_cell_ids=True)
        assert on["cell_ids"].dtype == np.uint64
        assert on.sizes["cells"] == 0

    def test_walk_fallback_empty(self, serc, tmp_path):
        # Same posture with no root MOC: the walk finds coverage, the AOI
        # misses it, the answer is still the schema-correct empty dataset.
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        (copy / convention.ROOT_COVERAGE_NAME).unlink()
        empty, _ = self._empty(str(copy))
        assert empty.sizes["cells"] == 0
        assert "count" in empty.data_vars

    def test_window_scoped_empty(self, serc, tmp_path):
        # The /2 pattern: a label in the store's vocabulary that holds no
        # data is a data answer (empty), not an error — the schema comes from
        # a stamped leaf in ANOTHER window (store-uniform schema).
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        manifest = json.loads((copy / convention.MANIFEST_NAME).read_text())
        manifest["spec"] = convention.HIVE_SPEC_V2
        manifest["temporal"] = {"schedule": "yearly", "time_field": "delta_time"}
        (copy / convention.MANIFEST_NAME).write_text(json.dumps(manifest))
        rel = convention.leaf_path(SERC_SHARD)
        (copy / rel).rename((copy / rel).parent / f"{SERC_SHARD}_2019.zarr")
        with pytest.warns(UserWarning, match="window '2020' intersects no coverage"):
            ds = open_hive(str(copy), window="2020")
        assert ds.sizes["cells"] == 0
        assert "count" in ds.data_vars
        # A label that fails the frozen grammar still raises, as before.
        with pytest.raises(ValueError, match="grammar"):
            open_hive(str(copy), window="20 20")

    def test_stale_root_moc_unscoped_raises(self, serc, tmp_path):
        # A STALE root MOC: the root coverage lists only a vanished leaf, yet
        # a committed leaf remains on disk unlisted (found by the schema
        # walk). An unscoped whole-store open must NOT silently return 0 cells
        # here — issue #4's empty contract is scoped to an AOI/window over no
        # coverage, so a whole-store open of a stale-indexed store raises,
        # naming the found leaf and pointing at regeneration.
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        envelope = json.loads((copy / convention.ROOT_COVERAGE_NAME).read_text())
        envelope["ranges"] = [["4331111", "4331111"]]  # an order-6 leaf never written
        (copy / convention.ROOT_COVERAGE_NAME).write_text(json.dumps(envelope))
        with pytest.raises(ValueError, match="stale root MOC"):
            open_hive(str(copy))
        # The #4 boundary, pinned: the SAME stale store opened AOI-scoped keeps
        # the empty-Dataset + UserWarning contract (scope is present, so the
        # stale-root raise does not fire).
        with pytest.warns(UserWarning, match="intersects no coverage"):
            ds = open_hive(str(copy), aoi=[OUTSIDE])
        assert ds.sizes["cells"] == 0
        assert "count" in ds.data_vars

    def test_no_stamped_coverage_raises(self, tmp_path):
        # The genuinely exceptional case: a hive root (manifest present) with
        # ZERO committed leaves has no schema source — NoCoverageError on any
        # open, AOI or not. Debris (templated but unstamped) is not coverage.
        from conftest import _manifest, _write_json, _zarr_group

        from moczarr import NoCoverageError

        root = tmp_path / "bare"
        _write_json(root / convention.MANIFEST_NAME, _manifest())
        _write_json(root / convention.leaf_path(SERC_SHARD) / "zarr.json", _zarr_group({}))
        with pytest.raises(NoCoverageError, match="no stamped coverage"):
            open_hive(str(root))
        with pytest.raises(NoCoverageError, match="no stamped coverage"):
            open_hive(str(root), aoi=[SERC_SHARD])
        with pytest.raises(ValueError):  # back-compat: still catchable as ValueError
            open_hive(str(root))


class TestSharedHandle:
    def test_constructions_are_o1(self, serc, monkeypatch):
        # Issue #5 acceptance: one open_hive call builds exactly ONE obstore
        # store plus ONE zarr ObjectStore wrapper (they are different
        # constructions — the wrapper adapts the shared obstore handle to the
        # zarr store API). Everything else — manifest, root MOC, stamps, and
        # all leaf opens — flows through that pair; the acceptance is O(1)
        # and these are the literals that fall out.
        import zarr.storage

        import moczarr.open as open_module
        from moczarr import store as store_module

        counts = {"obstore": 0, "wrapper": 0}
        real_open = store_module.open_object_store

        def counting_open(path, **kwargs):
            counts["obstore"] += 1
            return real_open(path, **kwargs)

        # Both bound names: store.py calls its module global, open.py its import.
        monkeypatch.setattr(store_module, "open_object_store", counting_open)
        monkeypatch.setattr(open_module, "open_object_store", counting_open)

        real_wrapper = zarr.storage.ObjectStore

        class CountingWrapper(real_wrapper):
            def __init__(self, *args, **kwargs):
                counts["wrapper"] += 1
                super().__init__(*args, **kwargs)

        monkeypatch.setattr(zarr.storage, "ObjectStore", CountingWrapper)
        open_hive(serc)
        assert counts == {"obstore": 1, "wrapper": 1}

    def test_deep_path_leaf_open(self, serc):
        # Pinned regression for the issue #5 spike: zarr v3 opens a leaf group
        # through the parentless digit tree by explicit path — it GETs
        # <path>/zarr.json directly and never consults parent metadata (the
        # hive tree has none at digit nodes, D5). This is the seam the shared
        # root-rooted wrapper depends on.
        import zarr
        from zarr.storage import ObjectStore

        wrapper = ObjectStore(store.open_object_store(serc), read_only=True)
        rel = convention.leaf_path(SERC_SHARD)
        group = zarr.open_group(wrapper, path=f"{rel}/8", mode="r")
        assert "morton" in group.array_keys()
        deep = xr.open_zarr(wrapper, group=f"{rel}/8", consolidated=False, zarr_format=3)
        manual = xr.open_zarr(f"{serc}/{rel}", group="8", consolidated=False, zarr_format=3)
        np.testing.assert_array_equal(deep["morton"].values, manual["morton"].values)
        np.testing.assert_array_equal(deep["count"].values, manual["count"].values)
        # And end to end: open_hive's result carries the same leaf slice
        # (test_matches_manual_leaf_open pins the values; here pin the route).
        ds = open_hive(serc, aoi=[SERC_SHARD])
        np.testing.assert_array_equal(
            np.asarray(ds["morton"].values, dtype=np.uint64),
            np.asarray(manual["morton"].values, dtype=np.uint64),
        )


class TestOpenHiveWalkFallback:
    def test_no_root_moc_degrades_to_walk(self, serc, tmp_path):
        # Same result with the root MOC deleted: the walk is the fallback,
        # never a different answer (D9).
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        (copy / convention.ROOT_COVERAGE_NAME).unlink()
        ds_walk = open_hive(str(copy))
        ds_moc = open_hive(str(FIXTURE))
        np.testing.assert_array_equal(ds_walk["morton"].values, ds_moc["morton"].values)
        np.testing.assert_array_equal(ds_walk["count"].values, ds_moc["count"].values)

    def test_walk_fallback_with_aoi(self, serc, tmp_path):
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        (copy / convention.ROOT_COVERAGE_NAME).unlink()
        ds = open_hive(str(copy), aoi=[SERC_SHARD])
        assert ds.sizes["cells"] == 16

    def test_windowed_store_without_window_lists_labels(self, serc, tmp_path):
        # A /2 store opened without window= errors with the labels that exist.
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        manifest = json.loads((copy / convention.MANIFEST_NAME).read_text())
        manifest["spec"] = convention.HIVE_SPEC_V2
        manifest["temporal"] = {"schedule": "yearly", "time_field": "delta_time"}
        (copy / convention.MANIFEST_NAME).write_text(json.dumps(manifest))
        # Rename one leaf to a windowed name so a label exists to report.
        rel = convention.leaf_path(SERC_SHARD)
        node = (copy / rel).parent
        (copy / rel).rename(node / f"{SERC_SHARD}_2019.zarr")
        with pytest.raises(ValueError, match="2019"):
            open_hive(str(copy))
        # And with the window given, the arithmetic path opens it.
        ds = open_hive(str(copy), window="2019", aoi=[SERC_SHARD])
        assert ds.sizes["cells"] == 16


class TestOpenHiveMocIndex:
    """``index_kind="moc"``: the lazy-index opener path (phase 5c).

    The acceptance is FULL equality against the pandas path — same data
    vars, same coordinate values (morton fabricated, cell_ids fabricated
    NESTED) — with zero coordinate-chunk reads.
    """

    def _assert_equal_datasets(self, want, got):
        assert set(want.variables) == set(got.variables)
        for name in want.variables:
            np.testing.assert_array_equal(want[name].values, got[name].values)
            assert want[name].dtype == got[name].dtype
        assert want.attrs["morton_hive"] == got.attrs["morton_hive"]

    def test_full_store_equality(self, serc):
        from moczarr.moc_index import MortonMocIndex

        want = open_hive(serc, index_kind="pandas")
        got = open_hive(serc, index_kind="moc")
        self._assert_equal_datasets(want, got)
        assert isinstance(got.xindexes["morton"], MortonMocIndex)
        assert "morton" not in want.xindexes  # the pandas posture stays index-free
        # The default IS the moc path (the phase-7d flip, issue #1).
        assert isinstance(open_hive(serc).xindexes["morton"], MortonMocIndex)

    @pytest.mark.parametrize(
        "aoi",
        [
            [SERC_SHARD],  # shard order
            ["433142224"],  # the occupied cell (cell order)
            [SERC_SHARD, "433124"],  # multiple shards
            ["43314"],  # coarser than shard order
        ],
    )
    def test_aoi_equality(self, serc, aoi):
        # Row domain = intervals ∩ AOI must equal the pandas path's aoi_mask
        # rows exactly (same leaf gating: stamps, box reject, empty mask).
        self._assert_equal_datasets(
            open_hive(serc, aoi=aoi), open_hive(serc, aoi=aoi, index_kind="moc")
        )

    def test_aoi_outside_coverage_is_empty(self, serc):
        # Issue #4 on the moc path: empty interval domain, index attached.
        from moczarr.moc_index import MortonMocIndex

        with pytest.warns(UserWarning, match="intersects no coverage"):
            ds = open_hive(serc, aoi=["-5112333"], index_kind="moc")
        assert ds.sizes["cells"] == 0
        assert isinstance(ds.xindexes["morton"], MortonMocIndex)
        assert ds.xindexes["morton"].size == 0

    def test_walk_fallback_equality(self, serc, tmp_path):
        # No root MOC: the domain builds from the walked shard list — same
        # arithmetic, same answer (D9).
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        (copy / convention.ROOT_COVERAGE_NAME).unlink()
        self._assert_equal_datasets(open_hive(str(copy)), open_hive(str(copy), index_kind="moc"))

    def test_morton_only_store(self, serc, tmp_path):
        # zagg#262 composition: on a store with no cell_ids arrays at all,
        # "auto" fabricates NESTED off the index's fabricated words — golden
        # parity against the original store's zagg-written array.
        from test_fabricate import _morton_only_copy

        golden = open_hive(serc, fabricate_cell_ids=False, index_kind="pandas")["cell_ids"].values
        ds = open_hive(_morton_only_copy(tmp_path), index_kind="moc")
        np.testing.assert_array_equal(ds["cell_ids"].values, golden)

    def test_fabricate_false_no_cell_ids(self, serc):
        ds = open_hive(serc, index_kind="moc", fabricate_cell_ids=False)
        assert "cell_ids" not in ds.variables

    def test_zero_coordinate_chunk_reads(self, serc, monkeypatch):
        # The plan's acceptance counter: a moc open GETs NO morton/cell_ids
        # chunk objects — even with an AOI, even with the data loaded — while
        # the pandas AOI path must read morton chunks (the row-mask truth).
        import obstore

        keys: list[str] = []
        real_get, real_get_async = obstore.get, obstore.get_async

        def record(store_, key, *args, **kwargs):
            keys.append(key)
            return real_get(store_, key, *args, **kwargs)

        def record_async(store_, key, *args, **kwargs):
            keys.append(key)
            return real_get_async(store_, key, *args, **kwargs)

        monkeypatch.setattr(obstore, "get", record)
        monkeypatch.setattr(obstore, "get_async", record_async)

        def coord_chunks():
            return [k for k in keys if "/morton/c" in k or "/cell_ids/c" in k]

        ds = open_hive(serc, aoi=[SERC_SHARD], index_kind="moc")
        ds["count"].values  # force the data reads; they must still flow
        assert coord_chunks() == []
        keys.clear()
        open_hive(serc, aoi=[SERC_SHARD], index_kind="pandas")
        assert coord_chunks() != []

    def test_invalid_index_kind_raises(self, serc):
        with pytest.raises(ValueError, match="index_kind"):
            open_hive(serc, index_kind="lazy")

    def test_decode_wraps_lazy_index(self, serc):
        dggs = pytest.importorskip("moczarr.dggs")
        from moczarr.moc_index import MortonMocIndex

        ds = open_hive(serc, index_kind="moc", decode=True)
        index = ds.xindexes["morton"]
        assert isinstance(index, dggs.MortonIndex)
        assert index._kind == "moc"
        assert isinstance(index._index, MortonMocIndex)
        # The accessor rides the lazy index; grid attrs round-trip.
        assert ds["morton"].attrs["grid_name"] == "morton"
        centers = ds.dggs.cell_centers()
        assert centers["latitude"].sizes["cells"] == ds.sizes["cells"]
        # sel through the wrapped index agrees with the core index.
        word = int(ds["morton"].values[5])
        assert int(ds.sel(morton=word)["count"]) == int(ds.isel(cells=5)["count"])

    def test_decode_moc_from_materialized_words(self, serc):
        # decode(index_kind="moc") on a dataset WITHOUT a lazy index —
        # run-detects the materialized coordinate into intervals.
        dggs = pytest.importorskip("moczarr.dggs")
        from moczarr.moc_index import MortonMocIndex

        ds = dggs.decode(open_hive(serc), index_kind="moc")
        assert isinstance(ds.xindexes["morton"]._index, MortonMocIndex)
        np.testing.assert_array_equal(ds["morton"].values, open_hive(serc)["morton"].values)

    def test_windowed_store_moc(self, serc, tmp_path):
        # The /2 arithmetic path composes: same leaf, lazy domain.
        copy = tmp_path / "serc"
        shutil.copytree(FIXTURE, copy)
        manifest = json.loads((copy / convention.MANIFEST_NAME).read_text())
        manifest["spec"] = convention.HIVE_SPEC_V2
        manifest["temporal"] = {"schedule": "yearly", "time_field": "delta_time"}
        (copy / convention.MANIFEST_NAME).write_text(json.dumps(manifest))
        rel = convention.leaf_path(SERC_SHARD)
        node = (copy / rel).parent
        (copy / rel).rename(node / f"{SERC_SHARD}_2019.zarr")
        want = open_hive(str(copy), window="2019", aoi=[SERC_SHARD])
        got = open_hive(str(copy), window="2019", aoi=[SERC_SHARD], index_kind="moc")
        self._assert_equal_datasets(want, got)

    def test_sel_isel_on_result(self, serc):
        # Integration smoke: label and positional selection on the opener's
        # lazy result (the deep flows are pinned in test_moc_index.py).
        ds = open_hive(serc, index_kind="moc")
        sub = ds.sel(morton=[int(w) for w in ds["morton"].values[4:8]])
        np.testing.assert_array_equal(
            sub["count"].values, ds.isel(cells=slice(4, 8))["count"].values
        )
