"""Spec-conformance decode of the committed zagg-written fixtures (issue #19).

Three fixtures, all produced by zagg's PRODUCTION write path and pinned by
committed expected values computed from the generator's *inputs* (never read
back through a zagg reader), so the reader is pinned, not self-certified:

- ``tests/data/spec/minimal`` and ``tests/data/spec/kitchen_sink`` — the
  spec §7 conformance vectors, vendored from englacial/zagg ``main`` at
  ``d52e3063`` as the **whole fixture tree, byte-identical** (re-verified
  ``diff -r`` at that sha): the leaf subtree each fixture's
  ``expected.json`` addresses (``1/1/2/1/3/11213.zarr``), ``morton_hive.json``
  (post-#420 ``semantic_hash``, ``zagg-pyramid/2`` declaration), and the
  pyramid-era surface beside the leaf — the §4.6 leaf column
  (``all.pyramid.zarr`` + ``all.pyramid.stats.json``) and the canonical-id
  ``granules.json`` (englacial/zagg#420). The vectors landed on ``main`` with
  the englacial/zagg#346 rebase merge (``c0493ba``); ``kitchen_sink``'s two
  ``*_locations`` arrays were re-pinned under the authalic latitude convention
  (mortie >=0.9.8, englacial/zagg#441). The branch-era shas ``166e908`` and
  ``555874b`` and the interim leaf-subset pins ``9e11e65``/``b9347561`` are
  historical.
- ``tests/data/spec/temporal`` — the §8.2/§8.3/§9 **companion** surface
  (englacial/zagg#410, PR #463; espg-ruled 2026-08-17: temporal companions
  are per-centroid at EVERY level, symmetric with located), vendored
  whole-tree byte-identical from the same ``d52e3063``: ``minimal``'s
  geometry with one digest field carrying BOTH companions
  (``h_tdigest_locations`` declaring ``zagg-located/1``,
  ``h_tdigest_times`` declaring ``zagg-toc/1`` at ``per-centroid``, bound
  from the payload's spec-owned ``times`` key), the dense per-cell
  ``observed`` toc array, and the §4.6 leaf column
  (``all.pyramid.zarr``) whose resolution-4/5 groups fold the payload AND
  both siblings — the fixture set's only golden for companions produced by
  a merge. This suite pins the words **byte-exactly** (decimal goldens, row
  alignment, the O11 hash gate against ``all.pyramid.stats.json``); the
  mortie-toc/1 word *semantics* (start/end ns, window predicates) are not
  yet adopted, so ``temporal.expected.json``'s containment data
  (``centroid_spans_ns``/``obs_span_ns``) is deliberately unasserted here.
- ``tests/data/strata_hive`` — the SERC-area strata fixture generated by
  ``tools/generate_strata_fixture.py`` from that same ``166e908`` checkout
  (recorded in ``strata_hive.expected.json`` as ``zagg_version:
  0.39.1.dev44+g166e908e4``), where ``src/zagg`` was byte-identical to
  ``origin/main``. One fixture serving issues #19/#20/#21; its tensor-level
  goldens live in ``tests/data/strata_goldens`` (consumed by
  ``test_hhdc.py``).

Everything here runs **without zagg installed**: decoding is
:mod:`moczarr.ragged` only, and the O11 cross-check is moczarr's own
:func:`moczarr.stats.hash_arrays`. Conformance is byte-exact float32/uint64
— no tolerance (spec §7).
"""

import json
from pathlib import Path

import numpy as np
import pytest
import zarr
from zarr.storage import LocalStore

from moczarr.pyramid import overview_declaration
from moczarr.ragged import (
    open_ragged,
    parse_companion_attrs,
    read_cell,
    read_ragged,
)
from moczarr.stats import combined_hash, hash_arrays

DATA = Path(__file__).parent / "data"
#: fixture name -> (store root, expected.json path).
FIXTURES = {
    "minimal": (DATA / "spec" / "minimal", DATA / "spec" / "minimal.expected.json"),
    "kitchen_sink": (
        DATA / "spec" / "kitchen_sink",
        DATA / "spec" / "kitchen_sink.expected.json",
    ),
    "temporal": (DATA / "spec" / "temporal", DATA / "spec" / "temporal.expected.json"),
    "strata_hive": (DATA / "strata_hive", DATA / "strata_hive.expected.json"),
}
STRATA_FIXTURES = ["kitchen_sink", "strata_hive"]
#: The temporal fixture's §4.6 leaf column, store-relative (spec §7).
PYRAMID_COLUMN = "1/1/2/1/3/all.pyramid.zarr"


def _load(name):
    root, expected_path = FIXTURES[name]
    expected = json.loads(expected_path.read_text())
    store = LocalStore(root / expected["leaf"])
    return store, expected


def _digest_field(name):
    return "h_tdigest_signal" if name in STRATA_FIXTURES else "h_tdigest"


def _expected_cells(expected, field):
    """``{morton_word: record}`` for cells whose ``field`` payload is nonempty."""
    return {
        int(cell["morton"]): cell
        for cell in expected["cells"]
        if cell.get(field)  # empty list = empty (0, 2) stratum payload
    }


@pytest.mark.parametrize("name", list(FIXTURES))
class TestDecodedValues:
    def test_digest_cells_match_expected_exactly(self, name):
        store, expected = _load(name)
        field = f"{expected['group']}/{_digest_field(name)}"
        cells = _expected_cells(expected, _digest_field(name))
        out = dict(read_ragged(store, field))
        assert set(out) == set(cells)
        for word, values in out.items():
            golden = np.array(cells[word][_digest_field(name)], dtype=np.float32)
            assert values.dtype == np.float32
            np.testing.assert_array_equal(values, golden)  # byte-exact, no tolerance

    def test_digest_payload_invariants(self, name):
        """Spec §2.1: means ascending, total weight = the exact obs count."""
        store, expected = _load(name)
        field = _digest_field(name)
        cells = _expected_cells(expected, field)
        merged_seen = False
        for word, values in read_ragged(store, f"{expected['group']}/{field}"):
            assert np.all(np.diff(values[:, 0]) >= 0)
            record = cells[word]
            exact = record["n_signal"] if field == "h_tdigest_signal" else record["count"]
            assert float(values[:, 1].sum()) == float(exact)
            merged_seen = merged_seen or bool(np.any(values[:, 1] > 1))
        assert merged_seen  # the 300-obs cell merges centroids (weight > 1)

    def test_empty_chunk_and_fill_cells_decode_empty(self, name):
        """The §1.5 absence sentinel and the §1.1 ``b""`` fill."""
        store, expected = _load(name)
        field = f"{expected['group']}/{_digest_field(name)}"
        per_chunk = expected["cells_per_chunk"]
        empty = expected["empty_chunk"]
        populated = {c["index"] for c in expected["cells"]}
        for cell in range(empty * per_chunk, (empty + 1) * per_chunk):
            assert read_cell(store, field, cell).shape == (0, 2)
        fill = next(i for i in range(per_chunk) if i not in populated)
        assert read_cell(store, field, fill).shape == (0, 2)

    def test_o11_content_hashes_match(self, name):
        """moczarr's own §5 O11 recipe reproduces the recorded hashes."""
        root, _ = FIXTURES[name]
        _store, expected = _load(name)
        hashes = hash_arrays(str(root), expected["leaf"])
        assert hashes == expected["content_hashes"]["arrays"]
        assert combined_hash(hashes) == expected["content_hashes"]["combined"]


@pytest.mark.parametrize("name", STRATA_FIXTURES)
class TestStrataFields:
    def test_located_strata_match_expected(self, name):
        """Payload + row-aligned location words, both strata, byte-exact —
        including the merged-centroid common-ancestor words (§2.2)."""
        store, expected = _load(name)
        for stratum in ("signal", "noise"):
            field = f"h_tdigest_{stratum}"
            cells = _expected_cells(expected, field)
            out = list(read_ragged(store, f"{expected['group']}/{field}", locations=True))
            assert {word for word, _v, _l in out} == set(cells)
            for word, values, locations in out:
                record = cells[word]
                np.testing.assert_array_equal(values, np.array(record[field], dtype=np.float32))
                golden_words = np.array(
                    [int(w) for w in record[f"{field}_locations"]], dtype=np.uint64
                )
                assert locations.dtype == np.uint64
                np.testing.assert_array_equal(locations, golden_words)

    def test_noise_only_cell_has_empty_signal_payload(self, name):
        """The empty ``(0, 2)`` stratum payload: observed cells whose signal
        stratum is empty store ``b""`` — decoded empty, never yielded."""
        store, expected = _load(name)
        noise_only = [c for c in expected["cells"] if c["count"] > 0 and not c["h_tdigest_signal"]]
        assert noise_only  # the fixture pins at least one such cell
        for cell in noise_only:
            values = read_cell(store, f"{expected['group']}/h_tdigest_signal", cell["index"])
            assert values.shape == (0, 2)

    def test_provenance_attrs_on_payload_only(self, name):
        """``stratum``/``signal_threshold`` land on the payload array; a
        sibling carries no USER attrs, only the spec-owned declaration its
        own section defines (spec §1.2) — none here: both these fixtures
        were committed before §9, which is the absent-``located`` pin."""
        store, expected = _load(name)
        group = expected["group"]
        arr, element = open_ragged(store, f"{group}/h_tdigest_signal")
        assert arr.attrs["stratum"] == "signal"
        assert int(arr.attrs["signal_threshold"]) == expected.get("signal_threshold", 2)
        assert element.locations == "h_tdigest_signal_locations"
        sibling, _ = open_ragged(store, f"{group}/{element.locations}")
        assert set(dict(sibling.attrs)) == {"ragged"}
        # §9 absent-key clause: never a refusal, parsed as "no declaration".
        assert parse_companion_attrs(dict(sibling.attrs), domain="located") is None


class TestTemporalCompanion:
    """The §8.3/§9 companion channels of the ``temporal/`` fixture, pinned on
    committed bytes — leaf ingest words and the §4.6 column's MERGED words
    (per-centroid at every level, the espg 2026-08-17 ruling amending zagg
    issue #410's ruling 3). Words are asserted byte-exactly; their
    mortie-toc/1 semantics are deliberately not decoded here (module
    docstring)."""

    def _expected(self):
        store, expected = _load("temporal")
        return store, expected

    def test_leaf_companion_words_match_expected(self):
        """Both channels, all four populated cells, byte-exact and
        row-aligned with the payload (spec §1.1/§8.3)."""
        store, expected = self._expected()
        cells = {int(c["morton"]): c for c in expected["cells"]}
        out = list(read_ragged(store, "6/h_tdigest", locations=True, times=True))
        assert {word for word, *_rest in out} == set(cells)
        for word, values, locations, times in out:
            record = cells[word]
            np.testing.assert_array_equal(values, np.array(record["h_tdigest"], dtype=np.float32))
            for got, key in ((locations, "h_tdigest_locations"), (times, "h_tdigest_times")):
                golden = np.array([int(w) for w in record[key]], dtype=np.uint64)
                assert got.dtype == np.uint64
                np.testing.assert_array_equal(got, golden)

    def test_companion_declarations_verbatim(self):
        """The three §8/§9 declaration blocks, exactly as ``expected.json``
        records them; the ``times`` binding on the payload; siblings carry
        the spec-owned declaration and nothing else (spec §1.2)."""
        store, expected = self._expected()
        arr, element = open_ragged(store, "6/h_tdigest")
        assert element.times == expected["times_binding"]
        assert arr.attrs["times"] == expected["times_binding"]
        assert element.locations == "h_tdigest_locations"
        for sibling, domain, attr in (
            ("h_tdigest_times", "temporal", "temporal"),
            ("h_tdigest_locations", "located", "located"),
        ):
            sib, _ = open_ragged(store, f"6/{sibling}")
            attrs = dict(sib.attrs)
            assert set(attrs) == {"ragged", attr}
            assert attrs[attr] == expected["declarations"][sibling]
            decl = parse_companion_attrs(attrs, domain=domain, field=sibling)
            assert decl is not None and decl.shape == "per-centroid"

    def test_observed_per_cell_words_match_expected(self):
        """The dense §8.2 companion: per-cell words byte-exact, the reserved
        ``0`` on unpopulated cells, the declaration verbatim — parsed
        POSITIVELY by a caller that names ``per-cell`` as the shape its path
        implements, and still refused under the ragged sibling path's
        default (§8's guessing-never rule)."""
        store, expected = self._expected()
        arr = zarr.open_array(store, path="6/observed", mode="r")
        attrs = dict(arr.attrs)
        assert attrs["temporal"] == expected["declarations"]["observed"]
        words = np.asarray(arr[:])
        populated = {c["index"]: int(c["observed"]) for c in expected["cells"]}
        for index in range(int(arr.shape[0])):
            assert int(words[index]) == populated.get(index, 0)
        decl = parse_companion_attrs(
            attrs, domain="temporal", field="6/observed", shapes=("per-cell",)
        )
        assert decl is not None and decl.shape == "per-cell"
        with pytest.raises(ValueError, match="per-cell"):
            parse_companion_attrs(attrs, domain="temporal", field="6/observed")

    @pytest.mark.parametrize("level", ["4", "5"])
    def test_overview_siblings_decode_via_the_leaf_path(self, level):
        """The §4.6 column's resolution groups decode through the SAME
        sibling path as the leaf (the point of the 2026-08-17 ruling): both
        channels bound by metadata, row-aligned with the folded payload,
        declarations identical to the leaf's."""
        root, _ = FIXTURES["temporal"]
        _store, expected = self._expected()
        column = LocalStore(root / PYRAMID_COLUMN)
        out = list(read_ragged(column, f"{level}/h_tdigest", locations=True, times=True))
        assert out  # every declared resolution group is populated
        for word, values, locations, times in out:
            assert values.dtype == np.float32 and values.shape[1:] == (2,)
            assert locations.dtype == np.uint64 and times.dtype == np.uint64
            assert len(locations) == len(values) == len(times)
        for sibling, domain in (
            ("h_tdigest_times", "temporal"),
            ("h_tdigest_locations", "located"),
        ):
            sib, _ = open_ragged(column, f"{level}/{sibling}")
            assert dict(sib.attrs)[domain] == expected["declarations"][sibling]

    def test_overview_count_is_the_exact_leaf_fold(self):
        """§4.5 exact-class conservation on committed bytes: each column
        level's ``count`` sums to the leaf's total observation count."""
        store, expected = self._expected()
        root, _ = FIXTURES["temporal"]
        total = sum(c["count"] for c in expected["cells"])
        leaf_count = zarr.open_array(store, path="6/count", mode="r")
        assert int(np.sum(leaf_count[:])) == total
        column = LocalStore(root / PYRAMID_COLUMN)
        for level in ("4", "5"):
            arr = zarr.open_array(column, path=f"{level}/count", mode="r")
            assert int(np.sum(np.asarray(arr[:]))) == total

    def test_pyramid_column_hashes_match_the_stats_sidecar(self):
        """moczarr's own §5 O11 recipe over the column's ten arrays — the
        six #463-added companion/payload chunks included — reproduces the
        ``all.pyramid.stats.json`` record, ``combined`` included."""
        root, _ = FIXTURES["temporal"]
        sidecar = json.loads((root / "1/1/2/1/3/all.pyramid.stats.json").read_text())[
            "content_hashes"
        ]
        hashes = hash_arrays(str(root), PYRAMID_COLUMN)
        assert hashes == sidecar["arrays"]
        assert combined_hash(hashes) == sidecar["combined"]

    def test_manifest_reclassifies_the_companioned_digest(self):
        """The #463 composability reclassification, from committed manifest
        bytes: ``h_tdigest`` folds (``approximate``, both companion keys),
        ``observed`` stays ``none``; and moczarr's /1 order-node reader
        reports NO overview family for the ``zagg-pyramid/2`` block (its
        ``overview`` mapping declares no legacy ``orders`` — the /2
        multiscale view is espg/moczarr#36/#37, not this reader)."""
        root, _ = FIXTURES["temporal"]
        manifest = json.loads((root / "morton_hive.json").read_text())
        assert manifest["pyramid"]["spec"] == "zagg-pyramid/2"
        fields = manifest["pyramid"]["overview"]["fields"]
        assert fields["h_tdigest"]["class"] == "approximate"
        assert fields["h_tdigest"]["temporal"] == "per-centroid"
        assert fields["h_tdigest"]["location"] == "leaf_id"
        assert fields["observed"] == {"class": "none"}
        assert fields["count"]["class"] == "exact"
        assert overview_declaration(manifest) is None
